/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lapsolver_generators_Grid2 */

#ifndef _Included_lapsolver_generators_Grid2
#define _Included_lapsolver_generators_Grid2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lapsolver_generators_Grid2
 * Method:    populateC
 * Signature: ([I[I[DIII)V
 */
JNIEXPORT void JNICALL Java_lapsolver_generators_Grid2_populateC
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
