/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lapsolver_generators_Hypercube */

#ifndef _Included_lapsolver_generators_Hypercube
#define _Included_lapsolver_generators_Hypercube
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lapsolver_generators_Hypercube
 * Method:    populateg4
 * Signature: ([I[I[DIIIIDDD)V
 */
JNIEXPORT void JNICALL Java_lapsolver_generators_Hypercube_populateg4
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jint, jint, jint, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
