/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lapsolver_generators_CBT */

#ifndef _Included_lapsolver_generators_CBT
#define _Included_lapsolver_generators_CBT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lapsolver_generators_CBT
 * Method:    populateCBT
 * Signature: ([I[I[DI)V
 */
JNIEXPORT void JNICALL Java_lapsolver_generators_CBT_populateCBT
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
