/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lapsolver_generators_Grid3 */

#ifndef _Included_lapsolver_generators_Grid3
#define _Included_lapsolver_generators_Grid3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lapsolver_generators_Grid3
 * Method:    populateg3
 * Signature: ([I[I[DIIIII)V
 */
JNIEXPORT void JNICALL Java_lapsolver_generators_Grid3_populateg3
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
